name: ${project.name}
version: ${project.version}
build: ${buildNumber}
main: ${main.class}
author: ${author}
api-version: 1.16

softdepend:
  - PlaceholderAPI
  - Vault


libraries:
  - com.google.code.gson:gson:2.8.9
  - org.apache.commons:commons-lang3:3.14.0